# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20170823_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='course_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
